replicaCount: 1

image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

livenessProbe: # 存活探针
   enabled: true
   initialDelaySeconds: 30 # 容器启动后第一次执行探测是需要等待多少秒。
   periodSeconds: 60 # 执行探测的频率。默认是10秒，最小1秒。
   timeoutSeconds: 5 # 探测超时时间。默认1秒，最小1秒。
   successThreshold: 1 # 探测失败后，最少连续探测成功多少次才被认定为成功。默认是1
   failureThreshold: 5 # 探测成功后，最少连续探测失败多少次才被认定为失败。默认是3

readinessProbe: # 就绪探针
   enabled: true
   initialDelaySeconds: 10
   periodSeconds: 10
   timeoutSeconds: 5
   successThreshold: 1
   failureThreshold: 5

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

persistence:
  enabled: true
  storageClass: "nfs-dynamic-class"    # 集群共享动态存储
  accessMode: ReadWriteOnce # 存储访问模式
  size: 30Mi   # 声明所需存储的大小
  annotations: {}

securityContext:
    enabled: true
    fsGroup: 0
    runAsUser: 0

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - demo.10.6.17.152.nip.io
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

nodeSelector: {}

tolerations: []

affinity: {}
